-- init.sql
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crawl_jobs (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  url VARCHAR(2048) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  depth INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pages (
  id SERIAL PRIMARY KEY,
  job_id INTEGER REFERENCES crawl_jobs(id) ON DELETE CASCADE,
  url VARCHAR(2048) UNIQUE NOT NULL,
  title TEXT,
  content TEXT,
  links_count INTEGER DEFAULT 0,
  crawled_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS page_links (
  id SERIAL PRIMARY KEY,
  page_id INTEGER REFERENCES pages(id) ON DELETE CASCADE,
  link_url TEXT
);

CREATE TABLE IF NOT EXISTS word_index (
  word TEXT,
  page_id INTEGER REFERENCES pages(id) ON DELETE CASCADE,
  frequency INTEGER DEFAULT 1,
  PRIMARY KEY(word, page_id)
);

CREATE INDEX IF NOT EXISTS idx_word ON word_index(word);
